services:
  api:
    build: 
      dockerfile: Dockerfile
      context: '.'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - app-data:/app/data
  postgres:
    image: postgres:10.4
    container_name: postgres_host

    ports:
      - "54321:5432"
    env_file:
      - .env
    volumes:
      - app-data:/var/lib/postgresql/data

volumes:
  app-data:


