services:
  backend:
    build: 
      dockerfile: Dockerfile
      context: '.'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3005
    ports:
      - "3005:3005"
    networks:
      - common-network
    volumes:
      - app-data:/app/data
  postgres:
    image: postgres:10.4
    container_name: postgres_host
    ports:
      - "54321:5432"
    env_file:
      - .env
    networks:
      - common-network
    volumes:
      - app-data:/var/lib/postgresql/data
  
  backend-nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy_backend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - common-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  frontend:
    build:
      dockerfile: Dockerfile
      context: '../../../Next/weather-app-frontend'
    container_name: frontend-app
    ports:
      - "3000:3000"
    networks:
      - common-network

volumes:
  app-data:

networks:
  common-network:
    external : true