services:
  api:
    build: 
      dockerfile: Dockerfile
      context: '.'
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3005
    ports:
      - "3005:3005"
    volumes:
      - app-data:/app/data
  postgres:
    image: postgres:10.4
    container_name: postgres_host
    ports:
      - "54321:5432"
    env_file:
      - .env
    volumes:
      - app-data:/var/lib/postgresql/data
  
  backend-nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy_backend
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  

volumes:
  app-data: